from flask import Flask, render_template, request
from googletrans import Translator, constants
import re, requests, lxml
from bs4 import BeautifulSoup

app = Flask(__name__)

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/result", methods=["POST"])
def result():

    #translator is feeling empy inside and waiting for someone to talk to it.
    translator = Translator()

    #get user input
    usrinp = request.form.get("input")
    #selected language
    lang_sel = request.form.get("lang")

    #translate and combine query with url
    destlang = translator.translate(usrinp, dest=lang_sel)

    #combine url with user input.
        #possible that this could be exchanged for other search engines.
    url = ('https://www.google.com/search?q=' + destlang.text)

    #user agent to assure google that it's not the end of the world
    headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

    #combine variables generated by user input
    r = requests.get(url, headers)
    
    #parse the data and do the first round of cleaning annd saving values. Rinse, repeat.
        #review later for ways to clean code and maybe abstract it. 
    htmlfile = BeautifulSoup(r.text, 'lxml')
    htmlfile = htmlfile.find("div", { "id" : "main" })
    htmlfile = htmlfile.select("a[href^='/url?q']")
    with open('templates/output.htm', 'w') as f:
        f.write(str(htmlfile))
    with open('templates/output.htm', 'r') as f:
        htmlfile = f.read()
        htmlfile = htmlfile.replace("/url?q=", "https://www.google.com/url?q=")
    with open('templates/output.htm', 'w') as f:
        f.write(str(htmlfile))
    links = BeautifulSoup(htmlfile, 'lxml')   
    url = links.find_all(href=True)
    with open('templates/output.htm', 'r') as f:
        soup = f.read()

    #reformatting and removing unwanted tags
    invalid_tags = ['div', 'html', 'body', 'p', 'h3', 'span']
    links = BeautifulSoup(soup, 'lxml')
    for tag in invalid_tags: 
        for match in links.findAll(tag):
            match.replaceWithChildren()

    print(type(links))
    #replace commas with div brackets to break up the container.
    links = re.sub(">, ", "></p></td></tr><tr><td><p>", str(links))

    # consider using list to deal with broken images
    #attr_tags = ['src=', 'style=', 'id=', 'class=']
    links = re.sub('src=', 'ignore=', str(links))
    links = re.sub('style=', 'ignore=', str(links))
    links = re.sub('id=', 'ignore=', str(links))

    #use of empty italics tag to nullify unwanted image data and preserve the alt attrbt as the anchore text
    links = re.sub('" class=', '<i ignore=', str(links))
    links = re.sub('></a>', '></i></a>', str(links))
    links = re.sub('<img alt="', '', str(links))
    
    #remove google links
    links = re.sub("Learn more", "", str(links))
    links = re.sub("Sign in", "", str(links))
    #links = re.sub("Preferences", "", str(links))

    #modify anchor to open in new tab
    links = re.sub("<a ", "<a target='_blank' ", str(links))

    #strip brackets
    links = (links.strip('[').strip(']'))
           
    return render_template("result.html", translation = destlang.text, links = links)

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)